// Code generated by "stringer -type=p2pInterfaceEvent"; DO NOT EDIT.

package p2p

import "strconv"

const _p2pInterfaceEvent_name = "StartedStopped"

var _p2pInterfaceEvent_index = [...]uint8{0, 7, 14}

func (i p2pInterfaceEvent) String() string {
	if i < 0 || i >= p2pInterfaceEvent(len(_p2pInterfaceEvent_index)-1) {
		return "p2pInterfaceEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _p2pInterfaceEvent_name[_p2pInterfaceEvent_index[i]:_p2pInterfaceEvent_index[i+1]]
}
