// Code generated by "stringer -type=peersInterfaceEvent"; DO NOT EDIT.

package p2p

import "strconv"

const _peersInterfaceEvent_name = "ActivePeersConnectedPeersDialledPeersDisconnectedPeersDiscoveredPeersMessagePeersProtocolPeers"

var _peersInterfaceEvent_index = [...]uint8{0, 11, 25, 37, 54, 69, 81, 94}

func (i peersInterfaceEvent) String() string {
	if i < 0 || i >= peersInterfaceEvent(len(_peersInterfaceEvent_index)-1) {
		return "peersInterfaceEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _peersInterfaceEvent_name[_peersInterfaceEvent_index[i]:_peersInterfaceEvent_index[i+1]]
}
