// Code generated by "stringer -type=syncStatus"; DO NOT EDIT.

package p2p

import "strconv"

const _syncStatus_name = "IdleSync"

var _syncStatus_index = [...]uint8{0, 4, 8}

func (i syncStatus) String() string {
	if i < 0 || i >= syncStatus(len(_syncStatus_index)-1) {
		return "syncStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _syncStatus_name[_syncStatus_index[i]:_syncStatus_index[i+1]]
}
