// Code generated by "stringer -type=encodingTypeEnum"; DO NOT EDIT.

package pair

import "strconv"

const _encodingTypeEnum_name = "XSalsa20_Poly1305None"

var _encodingTypeEnum_index = [...]uint8{0, 17, 21}

func (i encodingTypeEnum) String() string {
	if i < 0 || i >= encodingTypeEnum(len(_encodingTypeEnum_index)-1) {
		return "encodingTypeEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _encodingTypeEnum_name[_encodingTypeEnum_index[i]:_encodingTypeEnum_index[i+1]]
}
