// Code generated by "stringer -type=encodingContentEnum"; DO NOT EDIT.

package pair

import "strconv"

const _encodingContentEnum_name = "PKCS8"

var _encodingContentEnum_index = [...]uint8{0, 5}

func (i encodingContentEnum) String() string {
	if i < 0 || i >= encodingContentEnum(len(_encodingContentEnum_index)-1) {
		return "encodingContentEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _encodingContentEnum_name[_encodingContentEnum_index[i]:_encodingContentEnum_index[i+1]]
}
