package p2p

// TODO: merge with defaults sub-package?

import "fmt"

// DefaultClientID ...
var DefaultClientID = "golkadot/0.0.0"

// DefaultMaxPeers ...
var DefaultMaxPeers uint = 25

// DefaultPort ...
var DefaultPort uint = 30333

// DefaultAddress ...
var DefaultAddress = fmt.Sprintf("/ip4/0.0.0.0/tcp/%v", DefaultPort)

// DefaultProtocolPing ...
var DefaultProtocolPing = "/ipfs/ping/1.0.0"

// DefaultMaxRequestBlocks ...
var DefaultMaxRequestBlocks uint = 64

// DefaultProtocolBase ...
// TODO: change...
var DefaultProtocolBase = "/substrate"

// DefaultProtocolType ...
var DefaultProtocolType = "/sup"

// DefaultProtocolVersion ...
var DefaultProtocolVersion = 1

// DefaultRole ...
var DefaultRole = "full"

// DefaultMaxQueuedBlocks ...
var DefaultMaxQueuedBlocks = DefaultMaxRequestBlocks * 8

// DefaultMinIdleBlocks ...
var DefaultMinIdleBlocks = 16

// DefaultProtocolDot ...
var DefaultProtocolDot = fmt.Sprintf("%s%s/%d", DefaultProtocolBase, DefaultProtocolType, DefaultProtocolVersion)
