// Code generated by "stringer -type=digestEnum"; DO NOT EDIT.

package clienttypes

import "strconv"

const _digestEnum_name = "AuthoritiesChangeChangesTrieRootOtherSeal"

var _digestEnum_index = [...]uint8{0, 17, 32, 37, 41}

func (i digestEnum) String() string {
	if i < 0 || i >= digestEnum(len(_digestEnum_index)-1) {
		return "digestEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _digestEnum_name[_digestEnum_index[i]:_digestEnum_index[i+1]]
}
