// Code generated by "stringer -type=statusMessageRolesEnum"; DO NOT EDIT.

package clienttypes

import "strconv"

const (
	_statusMessageRolesEnum_name_0 = "NoneFullLight"
	_statusMessageRolesEnum_name_1 = "Authority"
)

var (
	_statusMessageRolesEnum_index_0 = [...]uint8{0, 4, 8, 13}
)

func (i statusMessageRolesEnum) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _statusMessageRolesEnum_name_0[_statusMessageRolesEnum_index_0[i]:_statusMessageRolesEnum_index_0[i+1]]
	case i == 4:
		return _statusMessageRolesEnum_name_1
	default:
		return "statusMessageRolesEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
