package sync

import (
	peertypes "github.com/c3systems/go-substrate/p2p/peer/types"
	synctypes "github.com/c3systems/go-substrate/p2p/sync/types"
)

// InterfaceSync defines the methods of the sync service
type InterfaceSync interface {
	// On handles events
	On(event synctypes.EventEnum, cb synctypes.EventCallback) (interface{}, error)
	// QueueBlocks ...
	// TODO ...
	QueueBlocks()
	// RequestBlocks ...
	// TODO ...
	RequestBlocks()
	// ProvideBlocks ...
	// TODO ...
	ProvideBlocks()
	// PeerRequests ...
	PeerRequests(pr peertypes.InterfacePeer) (Requests, error)
}
