package sync

import "github.com/c3systems/go-substrate/p2p/peer"

// InterfaceSync defines the methods of the sync service
type InterfaceSync interface {
	// On handles events
	On(event EventEnum, cb EventCallback) (interface{}, error)
	// QueueBlocks ...
	// TODO ...
	QueueBlocks()
	// RequestBlocks ...
	// TODO ...
	RequestBlocks()
	// ProvideBlocks ...
	// TODO ...
	ProvideBlocks()
	// PeerRequests ...
	PeerRequests(pr peer.Interface) (Requests, error)
}
